config/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views

urlpatterns = [
    #path('', views.index, name='index'), # 로그인 후, 로그아웃 후 url을 위해 매핑규칙을 같은걸 하나 더 추가
    path('', include('mainapp.urls')),
    path('user/', include('useradmin.urls')),
    path('admin/', admin.site.urls),
]

mainapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/type/<int:post_category>/', views.list, name='list'),
    path('post/id/<int:post_id>/', views.detail, name='detail'),
    path('comment/vote/<int:post_id>/', views.vote, name='vote'),
    path('comment/create/<int:post_id>/', views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

useradmin/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    # 장고의 django.contrib.auth기능을 이용하여 로그인과 로그아웃을 쉽게 구현가능하다.
    path('login/', auth_views.LoginView.as_view(template_name='useradmin/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    category = models.IntegerField() # 1~12까지로 한식부터 카페까지 구분하기 위한 필드
    subject = models.CharField(max_length=200) # 가게이름
    location = models.CharField(max_length=200) # 주소
    callnum = models.CharField(max_length=200) # 전화번호
    timeinfo = models.CharField(max_length=200) # 영업시간
    urlinfo = models.CharField(max_length=200) # URL
    menu = models.TextField() # 메뉴
    review = models.TextField() # 총평
    image = models.ImageField(blank=True, upload_to='media/') # 썸네일사진
    summary = models.CharField(max_length=200) # 썸네일텍스트
    voter = models.ManyToManyField(User, blank=True)  # 추천인

    def __str__(self):
        return self.subject

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    # 기존 모델을 속성으로 연결하려면 ForeignKey를 사용한다.
    # on_delete=models.CASCADE : 연결된 모델의 객체가 삭제될 경우 함께 삭제된다는 의미
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True) # 수정일시

useradmin/models.py
from django.db import models

# Create your models here.

mainapp/forms.py
from django import forms
from mainapp.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

useradmin/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    # UserCreationForm을 상속받고, 이메일 속성을 추가
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

    def clean_email(self):
        email = self.cleaned_data['email']
        if not email.endswith('@dankook.ac.kr'):
            raise forms.ValidationError("오직 단국대학교 학생들만 가입할 수 있습니다.")
        return email
    

mainapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages # 오류발생 창을 위한 messages

# Create your views here.
def index(request):
    return render(request, 'mainapp/lobby.html')

def list(request, post_category):
    # Post 중 해당하는 카테고리만 분류하여 반환
    # 1~11까지 한식~디저트
    post_list = Post.objects.filter(category=post_category) 
    context = {'post_list': post_list}
    return render(request, 'mainapp/list.html', context)

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id) # Question.objects.get의 상위호환이다. 실패하면 404오류를 전달
    context = {'post': post}
    return render(request, 'mainapp/detail.html', context) # question_detail.html에 있는 question에 context를 전달

@login_required(login_url='user:login')
def vote(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.voter.add(request.user) # 추천인 속성에 유저를 추가
    return redirect('main:detail', post_id=post.id)

@login_required(login_url='user:login')
def comment_create(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.create_date = timezone.now()
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('main:detail', post_id=post.id)
    else:
        form = CommentForm()
    context = {'post': post, 'form': form}
    return render(request, 'mainapp/detail.html', context)

@login_required(login_url='user:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('main:detail', post_id=comment.post.id)  
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment) # 새로운 내용으로 폼 업데이트후
        if form.is_valid():
            comment = form.save(commit=False) # 폼저장 (수정완료)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('main:detail', post_id=comment.post.id)
    else:
        form = CommentForm(instance=comment)
    context = {'comment': comment, 'form': form}
    return render(request, 'mainapp/detail_modify.html', context)

@login_required(login_url='user:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        comment.delete()
    return redirect('main:detail', post_id=comment.post.id)

useradmin/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from useradmin.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            # 만들어진 회원으로부터 아이디, 비번 가져와서 자동로그인 하게해준다.
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('main:index')
    else:
        form = UserForm()
    return render(request, 'useradmin/signup.html', {'form': form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <title>단국대 맛집추천 단슐랭</title>
</head>
<body>
    <!-- 공통으로 출력할 네비게이션 바를 구현 -->
    <div class="container">
        <header class="blog-header lh-1 py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="col-4 pt-1">   
                </div>
                <div class="col-4 text-center">
                    <a class="fs-1 fw-bold text-dark navbar-brand" href={% url 'main:index' %}>단슐랭</a>
                </div>
                <div class="col-4 d-flex justify-content-end align-items-center">
                    {% if not user.is_authenticated %}
                    <a class="fs-5 btn btn-basic" href={% url 'user:signup' %}>회원가입</a>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <a class="fs-5 link-secondary navbar-text" href={% url 'user:logout' %}>{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="fs-5 btn btn-basic" href={% url 'user:login' %}>로그인</a>
                    {% endif %}
                </div>
            </div>
        </header>
        <hr>
        <navbar class="navbar border border-2 border-secondary navbar-dark d-flex justify-content-between">
            <div class="container-fluid">
                <a class="fs-5 nav-link text-dark" href="{% url 'main:list' 1 %}">한식</a>
                <a class="fs-5 nav-link text-dark" href="{% url 'main:list' 2 %}">일식</a>
                <a class="fs-5 nav-link text-dark" href="{% url 'main:list' 3 %}">중식</a>
                <a class="fs-5 nav-link text-dark" href="{% url 'main:list' 4 %}">양식</a>
                <a class="fs-5 nav-link text-dark" href="{% url 'main:list' 5 %}">술집</a>
                <a class="fs-5 nav-link text-dark" href="{% url 'main:list' 6 %}">고깃집</a>
                <a class="fs-5 nav-link text-dark" href="{% url 'main:list' 7 %}">아시안</a>
                <a class="fs-5 nav-link text-dark" href="{% url 'main:list' 8 %}">치킨/피자</a>
                <a class="fs-5 nav-link text-dark" href="{% url 'main:list' 9 %}">패스트푸드</a>
                <a class="fs-5 nav-link text-dark" href="{% url 'main:list' 10 %}">분식/간편식</a>
                <a class="fs-5 nav-link text-dark" href="{% url 'main:list' 11 %}">카페/음료/디저트</a>   
            </div>
        </nav>
    </div>
    <main class="container">
    <!-- 상속받는 HTML파일의 Body가 들어가는 부분 -->
    {% block content %}
    {% endblock %}
    <!-- 상속받는 HTML파일의 Script가 들어가는 부분 -->
    </main>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    {% block script %}
    {% endblock %}
<!-- End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/mainapp/detail.html
{% extends 'base.html' %}
{% block content %}
<!-- 본문 시작 -->
<div class="container my-3 row row-cols-2">
    <div class="col-12">
        <h1 class="border-bottom py-2">{{ post.subject }}
            <a href="javascript:void(0)" data-uri="{% url 'main:vote' post.id  %}"
                class="recommend btn btn-outline-white"> <i class="text-success bi bi-hand-thumbs-up-fill"></i>
                <span class="">{{post.voter.count}}</span>
            </a>
        </h1>
    </div>
    <div class="col-12">
        <img class="rounded" width="50%" height="300" src="/media/{{post.image}}" alt="korean_post">
        <br><br>
    </div>
    <div class="col">
        <div class="mb-3">
            <h3 class="border-bottom py-2"><i class="align-bottom bi bi-house-door"></i> 주소</h3>
            <div class="card-text fs-5" style="white-space: pre-line;">{{ post.location }}</div>
        </div>
        <div class="mb-3">
            <h3 class="border-bottom py-2"><i class="align-bottom bi bi-telephone"></i> 전화번호</h3>
            <div class="card-text fs-5" style="white-space: pre-line;">{{ post.callnum }}</div>
        </div>
    </div>
    <div class="col">
        <div class="mb-3">
            <h3 class="border-bottom py-2"><i class="align-bottom bi bi-clock"></i> 영업시간</h3>
            <div class="card-text fs-5" style="white-space: pre-line;">{{ post.timeinfo }}</div>
        </div>
        <div class="mb-3">
            <h3 class="border-bottom py-2"><i class="align-bottom bi bi-link-45deg"></i> URL링크</h3>
            <div class="card-text fs-5" style="white-space: pre-line;"><a href="{{ post.urlinfo }}">{{ post.urlinfo }}</a></div>
        </div>
    </div>
</div>
<div class="container my-3 row">
    <div class="col-12">
        <h3 class="border-bottom py-2"><i class="align-bottom bi bi-journal-text"></i> 메뉴</h3>
        <div class="card my-3">
            <div class="card-body">    
                <div class="card-text fs-5" style="white-space: pre-line;">{{ post.menu }}</div>
            </div>
        </div>
    </div>  
    <div class="col-12">
        <h3 class="border-bottom py-2"><i class="align-bottom bi bi-info-circle"></i></i> 총평</h3>
        <div class="card my-3">
            <div class="card-body">    
                <div class="card-text fs-5" style="white-space: pre-line;">{{ post.review }}</div>
            </div>
        </div>
    </div>  
</div>
<!-- 의견 시작 -->
<div class="container my-3">
    <!-- 각 post 객체마다 있는 comment들을 출력해준다. -->
    <h4 class="border-bottom my-3 py-2"><i class="align-bottom bi bi-chat-dots"></i> {{post.comment_set.count}}개의 의견이 있습니다.</h4>
    {% for comment in post.comment_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                {% if comment.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">수정일시</div>
                    <div>{{ comment.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ comment.author.username }}</div>
                    <div>{{ comment.create_date }}</div>
                </div>
            </div>
            <div class="my-3"> <!-- 의견 수정 부분 -->
                {% if request.user == comment.author %}
                <a href="{% url 'main:comment_modify' comment.id  %}" 
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <!-- 삭제 시에 자바스크립트로 작성한 확인창을 띄우기 위해 href에 이렇게 연결한다. -->
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{% url 'main:comment_delete' comment.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 의견 작성 -->
    <form action="{% url 'main:comment_create' post.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">의견작성</label>
            <!-- 로그인 안했으면 의견작성을 불가능하게 막는다. -->
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="작성하기" class="btn btn-primary">
        <br><br><br>
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    // 의견 삭제 시의 사용할 자바스크립트, 즉 class="delete"일때 사용
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
                // 확인 누르면 data-uri에 적용된 링크가 실행
            };
        });
    });
    // 추천 시의 사용할 자바스크립트, 즉 class="recommend"일때 사용
    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("추천하시겠습니까?")) {
                location.href = this.dataset.uri; 
            };
        });
    });
</script>
{% endblock %}

templates/mainapp/detail_modify.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">의견수정</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">수정하기</button>
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
</script>
{% endblock %}

templates/mainapp/list.html
{% extends 'base.html' %}
{% block content %}
{% if post_list %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <!-- 게시글 시작 -->
            {% for post in post_list %}
            <div class="col">
                <a href="{% url 'main:detail' post.id %}" class="card shadow-sm fs-5 nav-link text-dark border border-3 border-drak">
                    <img class="rounded" width="100%" height="225" src="/media/{{post.image}}" alt="korean_post">
                    <div class="card-body">
                        <p class="card-text fs-4">{{ post.subject }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted fs-6">{{ post.summary }}</small>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
<br><br><br><br><br>
<p class="fs-2 text-secondary text-center">준비중입니다.</p>
{% endif %}
{% endblock %}
{% block script %}
<script type='text/javascript'>
</script>
{% endblock %}

templates/mainapp/list1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if post_list %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <!-- 게시글 시작 -->
            {% for post in post_list %}
            <div class="col">
                <a href="{% url 'main:detail' post.id %}" class="card shadow-sm fs-5 nav-link text-dark border border-3 border-drak">
                    <img class="rounded" width="100%" height="225" src="/media/{{post.image}}" alt="korean_post">
                    <div class="card-body">
                        <p class="card-text fs-4">{{ post.subject }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted fs-6">{{ post.location }}</small>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
<br><br><br><br><br>
<p class="fs-2 text-secondary text-center">준비중입니다.</p>
{% endif %}
{% endblock %}
{% block script %}
<script type='text/javascript'>
</script>
{% endblock %}
<!--
    <div class="col">
                <a href='#' class="card shadow-sm fs-5 nav-link text-dark border border-3 border-drak">
                    <img class="rounded" width="100%" height="225" src="{% static 'images/cuteruti.jpg' %}" alt="ruti">
                    <div class="card-body">
                        <p class="card-text">우리집 고양이 귀여운 루티</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted fs-6">평점 10.0</small>
                        </div>
                    </div>
                </a>
            </div>
-->

templates/mainapp/list2.html
{% extends 'base.html' %}
{% block content %}
{% if post_list %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <!-- 게시글 시작 -->
            {% for post in post_list %}
            <div class="col">
                <a href="{% url 'main:detail' post.id %}" class="card shadow-sm fs-5 nav-link text-dark border border-3 border-drak">
                    <img class="rounded" width="100%" height="225" src="/media/{{post.image}}" alt="korean_post">
                    <div class="card-body">
                        <p class="card-text fs-4">{{ post.subject }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted fs-6">{{ post.location }}</small>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
<br><br><br><br><br>
<p class="fs-2 text-secondary text-center">준비중입니다.</p>
{% endif %}
{% endblock %}
{% block script %}
<script type='text/javascript'>
</script>
{% endblock %}

templates/mainapp/list3.html
{% extends 'base.html' %}
{% block content %}
{% if post_list %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <!-- 게시글 시작 -->
            {% for post in post_list %}
            <div class="col">
                <a href="{% url 'main:detail' post.id %}" class="card shadow-sm fs-5 nav-link text-dark border border-3 border-drak">
                    <img class="rounded" width="100%" height="225" src="/media/{{post.image}}" alt="korean_post">
                    <div class="card-body">
                        <p class="card-text fs-4">{{ post.subject }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted fs-6">{{ post.location }}</small>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
<br><br><br><br><br>
<p class="fs-2 text-secondary text-center">준비중입니다.</p>
{% endif %}
{% endblock %}
{% block script %}
<script type='text/javascript'>
</script>
{% endblock %}

templates/mainapp/list4.html
{% extends 'base.html' %}
{% block content %}
{% if post_list %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <!-- 게시글 시작 -->
            {% for post in post_list %}
            <div class="col">
                <a href="{% url 'main:detail' post.id %}" class="card shadow-sm fs-5 nav-link text-dark border border-3 border-drak">
                    <img class="rounded" width="100%" height="225" src="/media/{{post.image}}" alt="korean_post">
                    <div class="card-body">
                        <p class="card-text fs-4">{{ post.subject }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted fs-6">{{ post.location }}</small>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
<br><br><br><br><br>
<p class="fs-2 text-secondary text-center">준비중입니다.</p>
{% endif %}
{% endblock %}
{% block script %}
<script type='text/javascript'>
</script>
{% endblock %}

templates/mainapp/lobby.html
{% extends 'base.html' %}
{% block content %}
<div class="p-4 p-md-5 mb-4 row text-bg-dark">
    <div class="col-md-6">
        <h1 class="display-4">단대생들을 위한 맛집가이드, 단슐랭</h1>
        <p class="lead my-3">"오늘 점심 뭐먹어야하지?", "술 어디서 마실래?", "어느 카페에서 공부해야할까?" 등 <span class="text-danger">여러분들의 식사 고민을 단슐랭이 단번에 해결해 드립니다.</span></p>
    </div>
    <div class="col-md-6">
        <img class="w-50 h-100 rounded-circle rounded mx-auto d-block" src="https://play-lh.googleusercontent.com/B28YgzJ6sVLUSGLDdMvvIXQaRBVIKbi83RahOChEn3tg_X_A9bCNfRpmbnZRit1DXKM" alt="michelin">
    </div>
</div>

<div class="row mb-2">
    <div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <p class="d-inline-block mb-2 text-primary fs-5">하나!</p>
            <h3 class="mb-0">폭넓은 카테고리</h3>
            <p class="card-text mb-auto fs-5 text-secondary">식사 상황에 맞춰 11가지의 카테고리 중 하나를 골라 열람할 수 있습니다.</p>
        </div>
    </div>
    </div>
    <div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <p class="d-inline-block mb-2 text-primary fs-5">둘!</p>
            <h3 class="mb-0">상세한 설명</h3>
            <p class="card-text mb-auto fs-5 text-secondary">매장의 영업시간, 위치, 전화번호, 메뉴까지 상세히 설명했습니다.</p>
        </div>
    </div>
    </div>
    <div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <p class="d-inline-block mb-2 text-primary fs-5">셋!</p>
            <h3 class="mb-0">추천 메뉴 확인</h3>
            <p class="card-text mb-auto fs-5 text-secondary">단국대 재학생인 단슐랭 제작자가 엄선한 추천 메뉴와 총평도 확인 가능합니다.</p>
        </div>
    </div>
    </div>
    <div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <p class="d-inline-block mb-2 text-primary fs-5">넷!</p>
            <h3 class="mb-0">추천 및 댓글 기능</h3>
            <p class="card-text mb-auto fs-5 text-secondary">매장별 단슐랭 회원들의 추천도와 댓글로 남긴 의견들을 볼 수 있습니다.</p>
        </div>
    </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
</script>
{% endblock %}

templates/useradmin/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3 py-5 row row-cols-3">
    <div class="col"></div>
    <form method="post" action="{% url 'user:login' %}">
        {% csrf_token %}
        <div class="col">
            <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
            {% include "form_errors.html" %}
            <div class="mb-3 fs-5">
                <label for="username">사용자ID</label>
                <input type="text" class="form-control" name="username" id="username"
                    value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3 fs-5">
                <label for="password">비밀번호</label>
                <input type="password" class="form-control" name="password" id="password"
                    value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <br>
            <button type="submit" class="btn btn-primary btn-lg">로그인</button>
        </div>
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
</script>
{% endblock %}

templates/useradmin/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3 py-5 row row-cols-3">
    <div class="col"></div>
    <form method="post" action="{% url 'user:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3 fs-5">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3 fs-5">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3 fs-5">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3 fs-5">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <br>
        <button type="submit" class="btn btn-primary btn-lg">생성하기</button>
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
</script>
{% endblock %}